### ISSUE TITLE
Relocate Contribution Docs

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx.github.io#10]
We currently have contribution docs here:
https://github.com/enarx/enarx.github.io/wiki/How-to-contribute

These need to be migrated to the standard place for GitHub. See this link for more details:
https://github.com/enarx/enarx.github.io/community

**Comment by axelsimon** [comment]
Done.
We now have https://github.com/enarx/enarx.github.io/blob/master/CONTRIBUTING.md as well as https://github.com/enarx/enarx/blob/master/CONTRIBUTING.md, which redirects to the above.

I will modify the CONTRIBUTING.md document to link back to wiki pages that split the advice for given domains and hold more specific instructions.
