### ISSUE TITLE
[Feature]: Add documentation for conventional commit for contributors

### ISSUE THREAD

**Issue by platten** [enarx/enarx.github.io#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Add documentation for conventional commit for contributors: https://www.conventionalcommits.org/en/v1.0.0/#summary

**Comment by bstrie** [comment]
@haraldh Can you link the document that you had written?

**Comment by haraldh** [comment]
@bstrie one comment above yours
