### ISSUE TITLE
[Feature]: Augment contributor documentation with requirements around conventional commits

### ISSUE THREAD

**Issue by platten** [enarx/enarx.github.io#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

With the newly enabled GitHub actions enforcing conventional commits, it is critical to provide appropriate guidance to the developer community on how to contribute content. 

### Acceptance Criteria

Update https://enarx.dev/docs/Contributing/PRs section of the website with the appropriate material around commit messages (as well as GitHub PR titles).

### Suggestions for a technical implementation

Please take a look at: https://github.com/dracutdevs/dracut/blob/master/docs/HACKING.md#commit-messages for inspiration.

Official spec here: https://www.conventionalcommits.org/en/v1.0.0/#summary

**Comment by nickvidal** [comment]
Hi Paul,

I've already expanded the existing Commit etiquette section to cover conventional commits over at:

https://enarx.dev/docs/Contributing/Coding-Style

Do we keep as is? Or should I move this section to the PR page?
