### ISSUE TITLE
[Feature]: Edit and post link to Enarx code walkthrough

### ISSUE THREAD

**Issue by platten** [enarx/enarx.github.io#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It would be helpful to edit and post @npmccallum's Enarx project code walkthrough video and make it easily consumable.

### Acceptance Criteria

- [x]  Break apart into sub-videos
- [x] Remove crosstalk/digressions/non-enarx related discussions
- [ ] Add sub-video topic splash graphic containing enarx logo & section title.
- [ ] Add opening and closing enarx project splash graphic (to first video and the last)
- [ ] Create draft blog post providing overview to video series along with private youtube playlist for review
- [ ] Approval/signoff by @npmccallum and/or @MikeCamel 
- [ ] Publish playlist & document/TOC in blog and/or post  for full walkthrough

**Comment by nickvidal** [comment]
I believe we can break the video down by these categories:
- Main crates: enarx and sallyport
- Secondary crates: key for enarx
- Helper crates: auxiliary
- Lab machines & workflow
- Documentation & outreach

I would have to record any missing video, but coverage is excellent.

## Main crates:

- [ ] enarx:
  - [X] src: code that runs in the host side. backends
  - [X] internal: wasmldr, shin-sev, shin-sgx
  - [X] examples: tcp_server
  - [ ] tests
  - [ ] helper
- [X] sallyport: communication channel between untrusted host and guest: mostly syscalls.

## Secondary crates:

- [X] ctr0stack: read write stack from Linux kernel for things like environment variables.
- [X] vsdo: used by sgx to enter an enclave
- [X] rct1: load binary from disk (static or dynamic)
- [X] xsave: save x86 cpu state
- [X] flagset: handle flags
- [X] sgx: set of data structures related to sgx
- [X] mmarinus: rust nmap (network mapper) wrapper
- [X] iocuddle: rust ioctl (input/output control) wrapper (runtime-safe)
- [X] noted: macro to generate notes (define size of enclave, etc)

## Helper crates

- [X] lset: types for measuring linear sets
- [X] nbytes: define constants
- [X] uabs: calculates the absolute value of input and returns unsigned integer
- [X] signrel: maps relationships between integers that only differ by signedness

## Lab machines & workflow

- [ ] gitlab.com/enarx: lab machines
- [X] linux: used by the lab machines (sgx and sev)
- [X] .github: templates for issues
- [X] spdx: github action to find OSI license

## Documentation & outreach

- [ ] enarx.github.io: website: documentation, resources, and community.
- [ ] outreach: outreach work
- [ ] outreachy: outreachy interns
