### ISSUE TITLE
[Feature]: Support enarx release-specific versions of enarx.dev

### ISSUE THREAD

**Issue by platten** [enarx/enarx.github.io#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

As there will be more documentation upcoming around features documented in enarx, it would be useful to have the site support multiple versions. This could also be helpful in installing the appropriate version in the install section, as well as help keeping the documentation in lock step with currently supported and unreleased enarx version. This would also allow the Install documentation to be different depending if you are installing from git or from published crates.

### Acceptance Criteria

- Design/proposal created
- Buy in from team
- Implementation of content
- Update in release automation

### Suggestions for a technical implementation

An example of this could be found [here](https://github.com/capactio/website).

**Comment by nickvidal** [comment]
Thank you, Paul! Adding this as a reference of how Docusaurus supports versioning:

https://docusaurus.io/docs/versioning
