### ISSUE TITLE
Can somebody explain me what is Trusted Execution Environment Please?

### ISSUE THREAD

**Issue by nishant0078** [enarx/enarx.github.io#21]

**Comment by nishant0078** [comment]
Can somebody explain me what is Trusted Execution Environment Please? #21

**Comment by axelsimon** [comment]
Hi Nishant, @lkatalin and i recently wrote an article about TEEs, what they are and the various flavours they come in:
https://next.redhat.com/2019/12/02/current-trusted-execution-environment-landscape/

This might answer some of your questions. Let me know if it helps!

**Comment by MikeCamel** [comment]
The Enarx Wiki also has some information which may be useful: [TEEs (Trusted Execution Environments)](https://github.com/enarx/enarx/wiki/TEEs-(Trusted-Execution-Environments))

**Comment by axelsimon** [comment]
@nishant0078 Have these resources helped you? I'd like to close this issue if possible :)
