### ISSUE TITLE
Update chat.enarx.io and chat.enarx.dev

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx.github.io#35]
https://desk.rocket.chat/portal/en/kb/articles/how-can-i-set-up-a-custom-domain

The new `CNAME` value is `cdns.use1.cloud.rocket.chat`. This is required before they can set up our certificate.

**Comment by axelsimon** [comment]
Ok, I'll ask the LF to update the DNS record.

**Comment by axelsimon** [comment]
It's done, for .dev @npmccallum :slightly_smiling_face: 
> chat.enarx.dev.         57      IN      CNAME   cdns.use1.cloud.rocket.chat.

I just saw you also wanted for .io. Wouldn't it make more sense to have a redirect from chat.enarx.io to chat.enarx.dev?

**Comment by axelsimon** [comment]
Redirect active, as mentioned in https://github.com/enarx/enarx/issues/637#issuecomment-662511700.
Done, closing :)
