### ISSUE TITLE
Overhaul Filling Issues Documentation

### ISSUE THREAD

**Issue by platten** [enarx/enarx.github.io#68]
# Description:
The current bug filling documentation requires an overhaul to ensure that the issue filing process is the coherent. This task is related to: https://github.com/enarx/.github/pull/11#issuecomment-1008872925

# Acceptance Criteria
- [x] Rename Bugs to "Filing Issues"
- [x] Add triage label to list of available labels
- [x] Provide information about filing a bug
- [x] Provide information about how to request a feature or enhancement

**Comment by nickvidal** [comment]
This is now complete. Will open a PR next time.

**Comment by nickvidal** [comment]
Closes #65 & #69
