### ISSUE TITLE
Create WebAssembly Guide with various languages

### ISSUE THREAD

**Issue by nickvidal** [enarx/enarx.github.io#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We want to create a WebAssembly Guide with a simple example using various programming languages that currently have support for WASI:

https://enarx.dev/docs/WebAssembly/Introduction

Fermyon has a good matrix showing languages that support WASI:

https://www.fermyon.com/wasm-languages/webassembly-language-support

Among these languages, recently we saw JavaScrip/TypeScript getting support:

https://blog.suborbital.dev/bringing-javascript-and-typescript-to-suborbital

### Acceptance Criteria

The languages we are interested in are the following, currently ordered by their support of WASI and importance:

- [x] Rust
- [x] C
- [x] C++
- [x] Go
- [x] JavaScript
- [x] TypeScript
- [x] AssemblyScript
- [x] Grain
- [x] Zig
- [ ] Ruby
- [ ] Swift
- [ ] C#
- [ ] Python
- [ ] Kotlin
- [ ] Erlang
- [ ] Haskell
- [ ] Lisp
- [ ] COBOL

### Suggestions for a technical implementation

We are thinking in using Fibonacci as an example:

https://github.com/enarx/outreachy/tree/main/Jennifer/Rust-to-WASI

If you are interested in contributing, please:

- Implement Fibonacci in your language of choice
- Add a markdown file to `docs/WebAssembly`
- Add a sidebar link at `sidebars.js`
- Create a PR against this `repo`

Thank you!

**Comment by Deepansharora27** [comment]
Shall I Raise another issue for the C++ Example or will embedding it here will work Nick ?

**Comment by Deepansharora27** [comment]
https://github.com/Deepansharora27/FibonacciEnarx
@nickvidal Hi Nick, 
This is my demo example for Fibonacci Example in C++ as well.

**Comment by jnyfah** [comment]
@moksh-pathak I have done that of Golang and rust, currently trying C# and python

**Comment by nickvidal** [comment]
If you are adventurous, you might want to explore AssemblyScript or Grain! :)

**Comment by moksh-pathak** [comment]
Would like to give it a shot!

**Comment by mayankkumar2** [comment]
@nickvidal is kotlin,Erlang,Haskell,C up for taking?

**Comment by nickvidal** [comment]
Hi @mayankkumar2, I believe @Deepansharora27 is working on the C example, but the other ones are open.

**Comment by Deepansharora27** [comment]
Yes right @nickvidal I have also made a Pull Request for the Same. 
Also I am now working on the Java and Kotlin side of things.
Telling so that it doesn't block the workflow for others 😊

**Comment by mayankkumar2** [comment]
Ok then, I will take up Haskell and Erlang.

**Comment by aryankaushik-git** [comment]
I would like to create the guide with javascript.

**Comment by mayankkumar2** [comment]
I tried out erlang and Haskell, the tooling is giving me some trouble. lumen's latest release seems to not even compile the hello world example, will have to build from source and document the same. For Haskell I got stuck with a weird error ```ahc-dist: internal error: Unable to commit 2902458368 bytes of memory```, have been trying to debug what's going wrong :(. The example code for both these languages seems to compile perfectly with their native compilers but not with the web assembly toolings.

**Comment by nickvidal** [comment]
Hi @mayankkumar2, no worries. Perhaps the tooling is "not there" yet.

Would you be interested in exploring Python (with @jnyfah ) or Java (with @Deepansharora27)?

**Comment by nickvidal** [comment]
Regarding Python, I got some recommendations from @tiran:

I just got WASI builds working with help of https://github.com/singlestore-labs/wasix .

```
$ wasmtime --mapdir=.::../.. -- ./python.wasm -c "import sys;
print(f'Hello {sys.platform} from {[sys.implementation.name](http://sys.implementation.name/)}')"
Hello wasi from cpython
```

You can find instructions and build container at
https://github.com/tiran/cpython_builddep/#webassembly-build . 

You have to run the command from a recent cpython git checkout. Next build a
native Python with ./build-python-build.sh and finally wasm32-wasi with
./build-python-wasi.sh

**Comment by Deepansharora27** [comment]
@mayankkumar2 You can connect with Jennifer for python for now as Java is something that I would like to work on independently till Sunday and maybe if issue still prevails , then we can connect together on Monday

**Comment by nickvidal** [comment]
Anyone with .NET knowledge who wants to try this?

https://github.com/SteveSandersonMS/dotnet-wasi-sdk

**Comment by Deepansharora27** [comment]
> Anyone with .NET knowledge who wants to try this?
> 
> https://github.com/SteveSandersonMS/dotnet-wasi-sdk

I would like to take this up

**Comment by nickvidal** [comment]
Anyone interested in exploring Ruby?

https://www.ruby-lang.org/en/news/2022/04/03/ruby-3-2-0-preview1-released/

**Comment by jnyfah** [comment]
> Anyone interested in exploring Ruby?
> 
> https://www.ruby-lang.org/en/news/2022/04/03/ruby-3-2-0-preview1-released/

I saw that some hours ago over Twitter, I have started checking it out

**Comment by IIITM-Jay** [comment]
Hi @nickvidal , an outreachy applicant here, 
 May I work on swift?

**Comment by moksh-pathak** [comment]
Hi @IIITM-Jay, I have already taken up the Swift WASM demo before.
